version: v2

config:
  contracts:
    evm:
      enabled: true
      solc: "0.8.26"
      framework: "hardhat"
      framework-version: "2.22.19"
      node-version: "22"
      package-manager: "npm"
      package-manager-version: "10.9.0"
    solana:
      enabled: false
  secrets:
    enabled: true
  iac:
    enabled: true
  dependencies:
    js:
      enabled: true
    rust:
      enabled: false
  compliance:
    genius:
      enabled: false

tasks:
  install-dependencies:
    - npm install